name: WebRTC Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "webRTC branch head. Ex: branch-heads/6167"
        required: true
        default: "branch-heads/0000"
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ninja-build python3 git curl wget lsb-release pkg-config

      - name: Configure CMake
        run: |
          mkdir -p build_cmake
          cd build_cmake
          cmake ..

      - name: Build WebRTC
        run: make -j$(nproc)

      - name: Create DEB Package
        run: cpack -G DEB

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-deb-package
          path: build_cmake/*.deb
